## numpy模块

- Numpy(Numerical Python)是python语言中做科学计算的基础库。重在于数值计算，也是大部分Python科学计算库的基础，多用在大型、多维数组上执行的数值运算。

### numpy的创建
- 使用np.array()创建
- 使用plt创建
- 使用np的routines函数创建

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

- 数组与列表的区别
    - 数组中存储的数据元素类型必须是统一类型
    - 优先级：
        - 字符串>浮点型>整数

In [4]:
arr=np.array([1,2,'three'])
arr

array(['1', '2', 'three'], dtype='<U11')

In [5]:
import matplotlib.pyplot as plt

img_arr = plt.imread('./1.jpg')
plt.imshow(img_arr)#将numpy数据进行可视化展示
img_arr =img_arr - 100# 将每一个数组元素都减去100

FileNotFoundError: [Errno 2] No such file or directory: './1.jpg'

In [6]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.linspace(0,100,num=20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [8]:
np.arange(10,50,step=2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
np.random.randint(0,100,size=(5,3))

array([[77, 94, 88],
       [36, 92, 67],
       [75, 54, 56],
       [ 8, 71, 33],
       [29,  3, 25]])

In [10]:
arr = np.random.randint(0,100,size=(5,6))
arr

array([[ 7, 98,  1, 11,  5, 81],
       [20, 69, 28, 86, 89, 51],
       [69, 74,  9,  4, 59, 40],
       [89, 10, 61, 32, 53, 13],
       [77, 48, 25,  7, 13, 90]])

In [11]:
arr.shape#返回的是数组的形状

(5, 6)

In [12]:
arr.ndim#数组的维度

2

In [13]:
arr.size#数组元素的个数


30

In [14]:
arr.dtype#返回的是数组元素类型

dtype('int32')

In [15]:
type(arr)#数组的类型

numpy.ndarray

In [17]:
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [18]:
arr.dtype = 'uint8'

In [19]:
arr.dtype

dtype('uint8')

In [4]:
arr = np.random.randint(1,100,size=(5,6))
arr

array([[40, 77, 67,  2, 94, 88],
       [70, 21, 41, 63,  4, 89],
       [37, 71, 90, 21, 72, 52],
       [90, 49, 38, 69, 38, 20],
       [12, 72, 67, 65, 58, 13]])

In [5]:
arr[1] #取出numpy数组中的下标为1的行数据

array([70, 21, 41, 63,  4, 89])

In [6]:
arr[[1,3,4]]#取出多行

array([[70, 21, 41, 63,  4, 89],
       [90, 49, 38, 69, 38, 20],
       [12, 72, 67, 65, 58, 13]])

In [8]:
#切出arr数组的前两行数据
arr[0:2]

array([[40, 77, 67,  2, 94, 88],
       [70, 21, 41, 63,  4, 89]])

In [12]:
#切出arr数组中的前两列
arr[:,0:2]#arr[行切片，列切片]

array([[40, 77],
       [70, 21],
       [37, 71],
       [90, 49],
       [12, 72]])

In [13]:
#将数组的行倒置
arr[::-1]

array([[12, 72, 67, 65, 58, 13],
       [90, 49, 38, 69, 38, 20],
       [37, 71, 90, 21, 72, 52],
       [70, 21, 41, 63,  4, 89],
       [40, 77, 67,  2, 94, 88]])

In [16]:
#将数组列倒置
arr[:,::-1]

array([[88, 94,  2, 67, 77, 40],
       [89,  4, 63, 41, 21, 70],
       [52, 72, 21, 90, 71, 37],
       [20, 38, 69, 38, 49, 90],
       [13, 58, 65, 67, 72, 12]])

In [18]:
#将所有元素倒置
arr[::-1,::-1]

array([[13, 58, 65, 67, 72, 12],
       [20, 38, 69, 38, 49, 90],
       [52, 72, 21, 90, 71, 37],
       [89,  4, 63, 41, 21, 70],
       [88, 94,  2, 67, 77, 40]])